=== suddha2/express/expresslk-services/ExpressLK-core/schema/taskBundle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:params="http://express.lk/2015/meta/parameters"
	xmlns:tbundle="http://express.lk/2015/meta/taskBundle"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	xmlns:meta="http://express.lk/2015/meta"
	targetNamespace="http://express.lk/2015/meta/taskBundle"
	elementFormDefault="qualified"
	jaxb:version="2.0">

	<xs:import schemaLocation="meta.xsd" namespace="http://express.lk/2015/meta"></xs:import>
	<xs:import schemaLocation="parameters.xsd" namespace="http://express.lk/2015/meta/parameters" />

	<xs:annotation>
		<xs:appinfo>
			<jaxb:schemaBindings>
				<jaxb:package name="lk.express.metaxml.tbundle" />
			</jaxb:schemaBindings>
		</xs:appinfo>
	</xs:annotation>

	<xs:element name="taskBundle" type="tbundle:taskBundleType" />

	<xs:complexType name="taskBundleType">
		<xs:sequence>
			<xs:element ref="meta:meta"></xs:element>
			<xs:element name="tasks" maxOccurs="1" minOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="task" type="tbundle:taskType" maxOccurs="unbounded" minOccurs="0" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="taskType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="groupName" type="xs:string" />
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="jobClass" type="xs:string" />
			<xs:element name="params" type="params:parametersType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="enabled" type="xs:boolean" use="required" />
	</xs:complexType>

	<xs:complexType name="recurringTaskType">
		<xs:complexContent>
			<xs:extension base="tbundle:taskType">
				<xs:sequence>
					<xs:element name="startTime" type="xs:dateTime" />
					<xs:element name="endTime" type="xs:dateTime" minOccurs="0" maxOccurs="1" />
					<xs:element name="repeatInterval" type="xs:int" />
					<xs:element name="durationType" type="tbundle:interval" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="oneTimeTaskType">
		<xs:complexContent>
			<xs:extension base="tbundle:taskType">
				<xs:sequence>
					<xs:element name="at" type="xs:dateTime" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="interval" final="restriction" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="MILLISECOND" />
			<xs:enumeration value="SECOND" />
			<xs:enumeration value="MINUTE" />
			<xs:enumeration value="HOUR" />
			<xs:enumeration value="DAY" />
			<xs:enumeration value="WEEK" />
			<xs:enumeration value="MONTH" />
			<xs:enumeration value="YEAR" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== suddha2/express/expresslk-services/ExpressLK-core/src/main/resources/files/metadata/taskBundle.xml
<?xml version="1.0" encoding="UTF-8"?>
<tbundle:taskBundle xmlns:meta="http://express.lk/2015/meta" xmlns:tbundle="http://express.lk/2015/meta/taskBundle"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:params="http://express.lk/2015/meta/parameters"
	xsi:schemaLocation="../../../../../schema/taskBundle.xsd ">
	<meta:processor>lk.express.meta.TaskBundleMetadata</meta:processor>
	<tbundle:tasks>
		<tbundle:task enabled="true" xsi:type="tbundle:recurringTaskType">
			<tbundle:name>Resource Releaser</tbundle:name>
			<tbundle:groupName>Core</tbundle:groupName>
			<tbundle:description>Release unconfirmed held items and tentative bookings</tbundle:description>
			<tbundle:jobClass>lk.express.tbundle.ResourceReleaser</tbundle:jobClass>
			<tbundle:startTime>2015-01-01T00:00:00</tbundle:startTime>
			<tbundle:repeatInterval>60</tbundle:repeatInterval>
			<tbundle:durationType>SECOND</tbundle:durationType>
		</tbundle:task>
		<!-- 
		<tbundle:task enabled="true" xsi:type="tbundle:recurringTaskType">
			<tbundle:name>Schedule Closer</tbundle:name>
			<tbundle:groupName>Core</tbundle:groupName>
			<tbundle:description>Closes schedules that have passed closing time</tbundle:description>
			<tbundle:jobClass>lk.express.tbundle.ScheduleCloser</tbundle:jobClass>
			<tbundle:startTime>2015-01-01T00:00:00</tbundle:startTime>
			<tbundle:repeatInterval>60</tbundle:repeatInterval>
			<tbundle:durationType>SECOND</tbundle:durationType>
		</tbundle:task>
		 -->
		<tbundle:task enabled="true" xsi:type="tbundle:recurringTaskType">
			<tbundle:name>Token Remover</tbundle:name>
			<tbundle:groupName>Core</tbundle:groupName>
			<tbundle:description>Remove expired API tokens</tbundle:description>
			<tbundle:jobClass>lk.express.tbundle.TokenRemover</tbundle:jobClass>
			<tbundle:startTime>2015-01-01T00:00:00</tbundle:startTime>
			<tbundle:repeatInterval>60</tbundle:repeatInterval>
			<tbundle:durationType>SECOND</tbundle:durationType>
		</tbundle:task>
	</tbundle:tasks>
</tbundle:taskBundle>
